# Generated by Django 3.2.25 on 2025-07-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='finish_rank',
        ),
    ]
