# Generated by Django 3.2.25 on 2025-07-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_entry_finish_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsepastrace',
            name='past_race_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
