# Generated by Django 3.2.25 on 2025-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_horsepastrace_body_weight_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsepastrace',
            name='distance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='距離(m)'),
        ),
    ]
