# Generated by Django 3.2.25 on 2025-07-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_horsepastrace_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horsepastrace',
            old_name='course_type',
            new_name='ground_condition',
        ),
    ]
