# Generated by Django 3.2.25 on 2025-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_course_type_horsepastrace_ground_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsepastrace',
            name='body_weight',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='馬体重'),
        ),
    ]
