# Generated by Django 3.2.25 on 2025-07-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_horsepastrace_body_weight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horsepastrace',
            unique_together={('horse', 'past_race_id')},
        ),
    ]
