# Generated by Django 3.2.25 on 2025-07-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_horsepastrace_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsepastrace',
            name='jockey_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='騎手ID'),
        ),
        migrations.AlterField(
            model_name='horsepastrace',
            name='jockey_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='騎手名'),
        ),
    ]
