# Generated by Django 3.2.25 on 2025-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20250716_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='レース順'),
        ),
    ]
