# Generated by Django 3.2.25 on 2025-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_race_race_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsepastrace',
            name='venue',
        ),
        migrations.AddField(
            model_name='horsepastrace',
            name='venue_day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='開催日目'),
        ),
        migrations.AddField(
            model_name='horsepastrace',
            name='venue_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='開催地'),
        ),
        migrations.AddField(
            model_name='horsepastrace',
            name='venue_round',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='開催回'),
        ),
    ]
