# Generated by Django 3.2.25 on 2025-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20250716_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsepastrace',
            name='last_3f_rank',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='上がり3Fの順番'),
        ),
    ]
