# Generated by Django 3.2.25 on 2025-07-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_horsepastrace_last_3f_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsepastrace',
            name='race_grade_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='レースグレードごとの点数'),
        ),
    ]
