# Generated by Django 3.2.25 on 2025-07-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_horsepastrace_race_grade_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_name', models.CharField(default='main_v1', max_length=100, verbose_name='AIモデル名')),
                ('notes', models.TextField(blank=True, verbose_name='メモ・見解')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('predicted_first', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_as_first', to='api.entry', verbose_name='1着予想')),
                ('predicted_second', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_as_second', to='api.entry', verbose_name='2着予想')),
                ('predicted_third', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_as_third', to='api.entry', verbose_name='3着予想')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.race', verbose_name='対象レース')),
            ],
            options={
                'verbose_name': 'AI予想',
                'verbose_name_plural': 'AI予想',
                'unique_together': {('race', 'prediction_model_name')},
            },
        ),
    ]
