# Generated by Django 3.2.25 on 2025-07-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_aiprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiprediction',
            name='predicted_first',
        ),
        migrations.RemoveField(
            model_name='aiprediction',
            name='predicted_second',
        ),
        migrations.RemoveField(
            model_name='aiprediction',
            name='predicted_third',
        ),
    ]
