# Generated by Django 3.2.25 on 2025-08-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20250725_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='head_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='頭数'),
        ),
    ]
