# version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    depends_on:
    - db
  frontend:
    build: ./frontend
    # volumes:
    #   - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: mysql:5.7
    env_file: .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: